---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shicongyang.
--- DateTime: 2019-06-12 15:55
---function 学习

local function foo()
    print("in the function")
    local x = 10
    local y = 20
    return x + y
end

local a = foo   -- 把函数赋给变量

print(a())