---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shicongyang.
--- DateTime: 2019-06-12 18:04
--- while

x = 1
sum = 0
while sum < 5 do
    sum = sum + x
    x = x + 1
end

print(sum)

local t = { 1, 3, 5, 8, 11, 18, 21 }

local i
for i, v in ipairs(t) do
    print("i:" .. i)
    print("v:" .. v)
    if 11 == v then
        print("index[" .. i .. "] have right value[11]")
        break
    end
end