---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shicongyang.
--- DateTime: 2019-06-12 17:30
---

--print("Hello " .. "World")    -->打印 Hello World
--print(0 .. 1)                 -->打印 01
--
--str1 = string.format("%s-%s","hello","world")
--print(str1)              -->打印 hello-world
--
--str2 = string.format("%d-%s-%.2f",123,"world",1.21)
--print(str2)              -->打印 123-world-1.21


---优先级（若不确定某些操作符的优先级，就应显示地用括号来指定运算顺序。这样做还可以提高代码的可读性。）
local a, b = 1, 2
local x, y = 3, 4
local i = 10
local res = 0
res = a + i < b / 2 + 1  -->等价于res =  (a + i) < ((b/2) + 1)
print(res)
res = 5 + x ^ 2 * 8        -->等价于res =  5 + ((x^2) * 8)
print(res)
res = a < y and y <= x  -->等价于res =  (a < y) and (y <= x)
print(res)