---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shicongyang.
--- DateTime: 2019-06-13 10:20
---

local _M = {}

local function get_name()
    return "Lucy"
end

function _M.greeting()
    print("hello " .. get_name())
end

return _M